
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu53788313f
 */
public class RecordsDialog extends javax.swing.JDialog {

    private class Record {

        public int record;
        public String name;

        public Record(int record, String name) {
            this.record = record;
            this.name = name;
        }
    }

    private static final String RECORD_FILE_NAME_SNAKE_EASY = "recordsSnakeEasy.txt";
    private static final String RECORD_FILE_NAME_SNAKE_MEDIUM = "recordsSnakeMedium.txt";
    private static final String RECORD_FILE_NAME_SNAKE_HARD = "recordsSnakeHard.txt";
    private int score;
    private JLabel[] recordLabels;
    private int minRecord;
    private ArrayList<Record> listOfRecords;

    /**
     * Creates new form RecordsDialog
     */
    public RecordsDialog(java.awt.Frame parent, boolean modal, int score) {
        super(parent, modal);
        initComponents();
        initRecordLabels();
        this.score = score;
        minRecord = 0;
        listOfRecords = new ArrayList<Record>();
        try {
            readRecords();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        processRecord();

    }

    private void processRecord() {
        JLabelCurrentScore.setText("Your score: " + score);

        if (score <= minRecord) {
            jLabelName.setVisible(false);
            jTextFieldName.setVisible(false);
        }
    }

    private void readRecords() throws FileNotFoundException, IOException {
        BufferedReader input = null;
        try {
            input = new BufferedReader(new FileReader(RECORD_FILE_NAME_SNAKE_EASY));
            int lineCount = 0;
            String line;
            String[] lineRecords = null;
            while (((line = input.readLine()) != null) && (lineCount < 5)) {
                lineRecords = line.split(".");
                recordLabels[lineCount].setText(lineRecords[0] + ": " + lineRecords[1]);
                lineCount++;
                listOfRecords.add(new Record(Integer.parseInt(lineRecords[0]), lineRecords[1]));
            }
            if (lineCount > 0) {
                try {
                    minRecord = Integer.parseInt(lineRecords[0]);
                } catch (NumberFormatException ex) {
                    ex.printStackTrace();
                }
            }

        } finally {
            if (input != null) {
                input.close();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        JLabelCurrentScore = new javax.swing.JLabel();
        jLabelRecord1 = new javax.swing.JLabel();
        jLabelRecord2 = new javax.swing.JLabel();
        jLabelRecord3 = new javax.swing.JLabel();
        jLabelRecord4 = new javax.swing.JLabel();
        jLabelRecord5 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelName.setText("Name");

        jTextFieldName.setText("jTextField1");
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        JLabelCurrentScore.setText("jLabel2");

        jLabelRecord1.setText("0. NoName");

        jLabelRecord2.setText("0. Noname");

        jLabelRecord3.setText("0. NoName");

        jLabelRecord4.setText("0. NoName");

        jLabelRecord5.setText("0. NoName");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabelCurrentScore, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                        .addGap(97, 97, 97))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelRecord5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelRecord4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelCurrentScore)
                .addGap(30, 30, 30)
                .addComponent(jLabelRecord1)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord2)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord3)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord4)
                .addGap(18, 18, 18)
                .addComponent(jLabelRecord5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        if (score > minRecord) {
            try {
                saveRecord();
               
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        } 
        dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void saveRecord() throws IOException {
        PrintWriter output = null;
        int lineCounter = 0;
        boolean alreadyWrittenScore = false;
        try {
            output = new PrintWriter(new FileWriter(RECORD_FILE_NAME_SNAKE_EASY));
            for (Record record : listOfRecords) {
                if (score > record.record && !alreadyWrittenScore);
                {
                    output.println(score + ", " + jTextFieldName.getText());
                    alreadyWrittenScore = true;
                    lineCounter++;
                } 
                if(lineCounter < 5){
                     output.println(record.record + ", " + record.name);
                     lineCounter++;
                }
            }
            if(!alreadyWrittenScore){
                output.println(score + ", " + jTextFieldName.getText());
            }
        } finally {
            if (output != null) {
                output.close();
            }
        }
    }
    
    public int getScore(){
        return score;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelCurrentScore;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRecord1;
    private javax.swing.JLabel jLabelRecord2;
    private javax.swing.JLabel jLabelRecord3;
    private javax.swing.JLabel jLabelRecord4;
    private javax.swing.JLabel jLabelRecord5;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    private void initRecordLabels() {
        recordLabels = new JLabel[5];
        recordLabels[0] = jLabelRecord1;
        recordLabels[1] = jLabelRecord2;
        recordLabels[2] = jLabelRecord3;
        recordLabels[3] = jLabelRecord4;
        recordLabels[4] = jLabelRecord5;

    }

}
